update concept sets for shared vars, uc1 vars, uc2 vars
thehyve/Capr-PHEMS pull request #4
Opened 2024-07-12 13:02 UTC by guuswilmink

2024-07-17 17:45 UTC, SofiaMp requested changes
We need to clean up a little bit the concept sets that have an "answer" also included because this wont be in the x_concept_id field. For example some measurement units are there or some severity.

2024-07-17 17:45 UTC, SofiaMp commented on project/R/conceptSets.R
> +      4273629, # source: Chemotherapy /// concept: Chemotherapy
this concepts appears also in line 34, one needs to be removed

2024-07-17 17:45 UTC, SofiaMp commented on project/R/conceptSets.R
> +      21603754, # source: Monoclonal Antibodies /// concept: Monoclonal antibodies
same in line 35

2024-07-17 17:45 UTC, SofiaMp commented on project/R/conceptSets.R
> +      1705674, # source: Trimethoprim-Sulfamethoxazole /// concept: trimethoprim
This would be better to move after line 46 to be clear they are from the same source

2024-07-17 17:45 UTC, SofiaMp commented on project/R/conceptSets.R
> +      1746114, # source: Piperacillin-Tazobactam /// concept: piperacillin
This would make more sense to move after line 71 as they have the same source

2024-07-17 17:45 UTC, SofiaMp commented on project/R/conceptSets.R
> +      1004025 # source: HR /// concept: Heart rate
This is a LOINC classification concept. Use [Heart rate](https://athena.ohdsi.org/search-terms/terms/3027018)

2024-07-19 12:56 UTC, LP-Glueck approved these changes

2024-07-19 13:25 UTC, merged