Update concept sets for UC1 tables 5.15 - 5.19 & UC3 tables
thehyve/Capr-PHEMS pull request #5
Opened 2024-07-12 13:47 UTC by LP-Glueck

Variables from UC3 have been added as csv files to phems_variables_list directory also in this PR.

I still need to finish the drug mappings as we don't have all the possible mappings specified for the Factor VIII treatment variable (There can be potentially a lot). I will check if descendants can be used at all, but I think I will have to specify all possible drug mappings that we gave them as options because they are not subsumes of each other.

2024-07-17 10:30 UTC, SofiaMp requested changes
Found some concepts that can change. Only minor things. I understand that the csv files would need to be updated but I did not add the comments there.

2024-07-17 10:30 UTC, SofiaMp commented on project/R/conceptSets.R
> +      4096101 # source: SpO2 /// concept: Measurement of oxygen saturation at periphery
Maybe a better concept: [Oxygen saturation measurement](https://athena.ohdsi.org/search-terms/terms/4020553)

2024-07-17 10:30 UTC, SofiaMp commented on project/R/conceptSets.R
> +      44790138, # source: Deep hypothermic circulatory arrest start datetime, end datetime /// concept: Induced circulatory arrest
Maybe a better concept: [Hypothermic circulatory arrest](https://athena.ohdsi.org/search-terms/terms/37152781)

2024-07-17 10:30 UTC, SofiaMp commented on project/R/conceptSets.R
> +      794078, # source: Dose of vasoactive infusion (rate - mcg/kg/hr) /// concept: vasoactive intestinal peptide
This doesn't need to be a concept but can be derived from the dose field of drug exposure record for the vasoactive drug.

2024-07-17 10:30 UTC, SofiaMp commented on project/R/conceptSets.R
> +      37393863, # source: platelet count /// concept: platelet count
This is a not standard concept. The standard one is: [Platelet count](https://athena.ohdsi.org/search-terms/terms/4267147)

2024-07-17 10:30 UTC, SofiaMp commented on project/R/conceptSets.R
> +      45888085, # source: Medical/ surgical procedure /// concept: medical procedure
This concept is a CPT4 classification code for [Surgery](https://athena.ohdsi.org/search-terms/terms/45888085). Use instead [Therapeutic procedure](https://athena.ohdsi.org/search-terms/terms/4172515)

2024-07-17 10:30 UTC, SofiaMp commented on project/R/conceptSets.R
> +      45888867, # source: datetime start anesthesia /// concept: anesthesia
This concept is also a CPT4 classification code. Use instead [Administration of anesthesia](https://athena.ohdsi.org/search-terms/terms/4160439)

2024-07-17 10:30 UTC, SofiaMp commented on project/R/conceptSets.R
> +      37017589 # source: blood transfusion during surgery /// concept: bleeding during medical procedure requiring transfusion
The concept name is slightly different [Bleeding during surgery requiring transfusion](https://athena.ohdsi.org/search-terms/terms/37017589)

2024-07-19 07:02 UTC, LP-Glueck commented
Ready for review with updated changes 👍🏼

2024-07-19 10:15 UTC, guuswilmink commented
Please add some comments to the conceptSets to indicate the source table from D4.1
For example for vital signs;
#  5.22 Vital Signs
vitalSigns = c(
  ...  # source: <> \\\ concept: <>
)

Other than that looks good! You can merge after this change

2024-07-19 10:16 UTC, guuswilmink approved these changes

2024-07-19 12:50 UTC, merged